# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]                                         # Define a profile name
url = "https://rpc.starknet-testnet.lava.build"          # Url of the RPC provider
account = "deployer"                                     # Account from `accounts_file` or default account file that will be used for the transactions
wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer
